---
title: "Data Manipulation"
output: github_document
---

```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)


```

This document will show how to *manipulate* data. 

Import the two datasets that we're going to manipulate


```{r}
litters_df = read_csv("data/FAS_litters.csv", na = c("NA", "", ".'"))
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data/FAS_pups.csv", na = c("NA", "", ".'"))
pups_df= janitor::clean_names(pups_df)  
```

## `select`

Use `select()` to select variables 
```{r}
select(litters_df, group, litter_number, gd0_weight)

select(litters_df, group:gd18_weight)

select(litters_df, -pups_survive)


select(litters_df, -(group:gd18_weight))

select(litters_df, starts_with("gd"))

select(litters_df, contains("pups"))

select(litters_df, GROUP = group)

rename(litters_df, GROUP = group)

select(litters_df, litter_number, group)

relocate(litters_df, litter_number, pups_survive)

```


## `filter`

## `mutate`

## `arrange`


## `PIPING`    



```{r}

```

