---
title: "Tidy Data"
output: github_document
---

```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl) 
library(haven)

```

This document will show how to tidy data. 

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
```


##Pivot Longer
```{r}
pulse_tidy_df = 
  pulse_df |>
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to ="visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl","00m")
  ) |> 
  relocate(id, visit)
```
Do one more example 

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |>
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  )|> 
  mutate(
    gd_time = case_match(
      gd_time, 
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    ))
```
#Pivot Wider

Lets make up an analysis results table 
```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )
```

Pivot Wider for Human Redability 
```{r}
pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean") |> 
  knitr::kable()
```
##Bind tables
```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring") 

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")
```

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") |>
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything())
```